## Omnichannel Retail Sales and Inventory Analytics

##### Week 1: Data Collection, Environment Setup, and Initial Cleaning
The inaugural week demands the establishment of the foundational infrastructure. Interns must
initiate the GitHub repository, configuring it to track their Jupyter Notebooks and SQL scripts.
The intern will import the raw retail dataset into Python/Excel to begin the Data Cleaning phase.
Tasks include identifying and handling NULL values, removing duplicate records, standardizing
date/time formats, and validating data types across all columns.

# What we have to do for this week

1. Github repo
2. Collect dataset
3. import the dataset into python / excel
4. Data cleaning
5. Data Validation

### Importing library & dataset

In [7]:
# importing numpy & pandas

import numpy as np
import pandas as pd

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Initial Data Exploration

In [16]:
# read a file
raw_data = pd.read_csv('/content/sample_data/retail_store_inventory.csv')
print(raw_data)

             Date Store ID Product ID     Category Region  Inventory Level  \
0      01-01-2022     S001      P0001    Groceries  North              231
1      01-01-2022     S001      P0002         Toys  South              204
2      01-01-2022     S001      P0003         Toys   West              102
3      01-01-2022     S001      P0004         Toys  North              469
4      01-01-2022     S001      P0005  Electronics   East              166
...           ...      ...        ...          ...    ...              ...
73095  01-01-2024     S005      P0016    Furniture   East               96
73096  01-01-2024     S005      P0017         Toys  North              313
73097  01-01-2024     S005      P0018     Clothing   West              278
73098  01-01-2024     S005      P0019         Toys   East              374
73099  01-01-2024     S005      P0020    Groceries   East              117

       Units Sold  Units Ordered  Demand Forecast  Price  Discount  \
0             127             55           135.47  33.50        20
1             150             66           144.04  63.01        20
2              65             51            74.02  27.99        10
3              61            164            62.18  32.72        10
4              14            135             9.26  73.64         0
...           ...            ...              ...    ...       ...
73095           8            127            18.46  73.73        20
73096          51            101            48.43  82.57        10
73097          36            151            39.65  11.11        10
73098         264             21           270.52  53.14        20
73099           6            165             2.33  78.39        20

      Weather Condition  Holiday/Promotion  Competitor Pricing Seasonality
0                 Rainy                  0               29.69      Autumn
1                 Sunny                  0               66.16      Autumn
2                 Sunny                  1               31.32      Summer
3                Cloudy                  1               34.74      Autumn
4                 Sunny                  0               68.95      Summer
...                 ...                ...                 ...         ...
73095             Snowy                  0               72.45      Winter
73096            Cloudy                  0               83.78      Autumn
73097             Rainy                  0               10.91      Winter
73098             Rainy                  0               55.80      Spring
73099             Rainy                  1               79.52      Spring

[73100 rows x 15 columns]

In [17]:
raw_data.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,01-01-2022,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,01-01-2022,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,01-01-2022,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,01-01-2022,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,01-01-2022,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [18]:
raw_data.tail()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
73095,01-01-2024,S005,P0016,Furniture,East,96,8,127,18.46,73.73,20,Snowy,0,72.45,Winter
73096,01-01-2024,S005,P0017,Toys,North,313,51,101,48.43,82.57,10,Cloudy,0,83.78,Autumn
73097,01-01-2024,S005,P0018,Clothing,West,278,36,151,39.65,11.11,10,Rainy,0,10.91,Winter
73098,01-01-2024,S005,P0019,Toys,East,374,264,21,270.52,53.14,20,Rainy,0,55.80,Spring
73099,01-01-2024,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring

In [19]:
raw_data.columns

Index(['Date', 'Store ID', 'Product ID', 'Category', 'Region',
       'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast',
       'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion',
       'Competitor Pricing', 'Seasonality'],
      dtype='object')

In [20]:
raw_data.dtypes

Date                   object
Store ID               object
Product ID             object
Category               object
Region                 object
Inventory Level         int64
Units Sold              int64
Units Ordered           int64
Demand Forecast       float64
Price                 float64
Discount                int64
Weather Condition      object
Holiday/Promotion       int64
Competitor Pricing    float64
Seasonality            object
dtype: object

In [21]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 8.4+ MB

In [22]:
# date in object format -> convert into date
raw_data['Date'].dtypes

dtype('O')

In [23]:
raw_data.shape

(73100, 15)

In [24]:
raw_data.size

1096500

In [25]:
raw_data.describe()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Holiday/Promotion,Competitor Pricing
count,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,0.497305,55.146077
std,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,0.499996,26.191408
min,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,0.000000,5.030000
25%,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,0.000000,32.680000
50%,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,0.000000,55.010000
75%,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,1.000000,77.820000
max,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,1.000000,104.940000

In [26]:
raw_data.sample()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
56923,24-07-2023,S002,P0004,Furniture,West,314,75,195,77.39,71.94,15,Snowy,1,73.91,Autumn

In [27]:
raw_data.nunique()

Date                    731
Store ID                  5
Product ID               20
Category                  5
Region                    4
Inventory Level         451
Units Sold              498
Units Ordered           181
Demand Forecast       31608
Price                  8999
Discount                  5
Weather Condition         4
Holiday/Promotion         2
Competitor Pricing     9751
Seasonality               4
dtype: int64

### Data Cleaning

#### 1.Check null

In [28]:
raw_data.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [29]:
raw_data.dropna(inplace=True)

#### 2. Check duplicates & remove it

In [30]:
raw_data.duplicated().sum()

np.int64(0)

In [31]:
raw_data.drop_duplicates(inplace=True)

In [32]:
raw_data.shape

(73100, 15)

## Download cleaned dataset

In [37]:
raw_data.to_csv('Cleaned_retail_inventory_data.csv',index=False)

In [38]:
cleaned_data = pd.read_csv('/content/Cleaned_retail_inventory_data.csv')
cleaned_data.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,01-01-2022,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,01-01-2022,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,01-01-2022,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,01-01-2022,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,01-01-2022,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer